### ISSUE TITLE
Add Contributing.md file 

### ISSUE THREAD

**Issue by willparr** [bradgarropy/hue-sdk#7]
For new people adding to the repo, it would be nice to know what the process should be:
- When to mark PR ready vs draft
- Coding style (seems like functional expressions are used vs methods or the function keyword)
- Just other general housekeeping things

**Comment by bradgarropy** [comment]
Thanks for opening this up, this is my first repo to get any real contributions so I definitely need to add a `CONTRIBUTING` file!

**Comment by bradgarropy** [comment]
Some resources for reference.

- https://makeapullrequest.com
- https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
- https://github.com/testing-library/react-testing-library/blob/master/CONTRIBUTING.md
- https://github.com/date-fns/date-fns/blob/master/CONTRIBUTING.md
- https://github.com/facebook/jest/blob/master/CONTRIBUTING.md
